name: Auto PR to keptn/keptn
on:
  push:
    branches:
      - 'master'
      - 'release-*'
    tags:
      - 'v*'
jobs:
  auto-pr:
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Checkout keptn/keptn repo
        uses: actions/checkout@v2.3.4
        with:
          path: 'keptn'
          repository: 'keptn/keptn'
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          ref: 'master'
      - name: Determine Target CommitIsh
        id: target_commit
        run: |
          KUBERNETES_UTILS_TARGET="${{ github.sha }}"
          echo "##[set-output name=KUBERNETES_UTILS_TARGET;]$(echo ${KUBERNETES_UTILS_TARGET})"
          TARGET_BRANCH=patch/go_utils_${KUBERNETES_UTILS_TARGET}
          echo "##[set-output name=TARGET_BRANCH;]$(echo ${TARGET_BRANCH})"
      - name: Auto update go mod
        working-directory: 'keptn'
        env:
          KUBERNETES_UTILS_TARGET: ${{ steps.target_commit.outputs.KUBERNETES_UTILS_TARGET }}
        run: ../gh-actions-scripts/auto-update-go-mod.sh "${KUBERNETES_UTILS_TARGET}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: 'keptn'
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          commit-message: "Update keptn/kubernetes-utils to ${{ steps.target_commit.outputs.KUBERNETES_UTILS_TARGET }}"
          committer: "keptn-bot <86361500+keptn-bot@users.noreply.github.com>"
          author: "keptn-bot <86361500+keptn-bot@users.noreply.github.com>"
          signoff: true
          branch: ${{ steps.target_commit.outputs.TARGET_BRANCH }}
          delete-branch: true
          base: master
          labels: "area:kubernetes-utils,automated pr,dependencies"
          title: "Auto-update kubernetes-utils to latest version"
          body: |
            **This is an automated PR!**

            This is an automatically created PR to change [keptn/kubernetes-utils](https://github.com/keptn/kubernetes-utils) to version ${{ steps.target_commit.outputs.KUBERNETES_UTILS_TARGET }}.
            Please consult https://github.com/keptn/kubernetes-utils/actions?query=workflow%3A%22Auto+PR+to+keptn%2Fkeptn%22 for more information.
