name: Update kubernetes-utils in keptn/keptn
on:
  push:
    branches:
      - 'master'
      - 'release-*'
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  send_webhook:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger kubernetes-utils auto update in core repo
        if: github.event_name == 'workflow_dispatch'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          repository: 'keptn/keptn'
          event-type: k8s-utils-update
          client-payload: '{"k8s-utils-target": "${{ github.sha }}"}'
      - name: Trigger kubernetes-utils auto update in core repo
        if: github.event_name == 'push'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.KEPTN_BOT_TOKEN }}
          repository: 'keptn/keptn'
          event-type: k8s-utils-update
          client-payload: '{"k8s-utils-target": "${{ github.sha }}"}'
